TrainTicketSales/Models/Entity/Cabin.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class Cabin
    {
        public Cabin()
        {
            Seat = new HashSet<Seat>();
        }

        public long Id { get; set; }
        public string CabinCategoryCode { get; set; }
        public string Index { get; set; }
        public string TrainCode { get; set; }

        public virtual CabinCategory CabinCategoryCodeNavigation { get; set; }
        public virtual Train TrainCodeNavigation { get; set; }
        public virtual ICollection<Seat> Seat { get; set; }
    }
}

TrainTicketSales/Areas/Admin/Controllers/CabinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrainTicketSales.Models.Entity;

namespace TrainTicketSales.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CabinsController : Controller
    {
        private readonly DsvnContext _context;

        public CabinsController(DsvnContext context)
        {
            _context = context;
        }

        // GET: Admin/Cabins
        public async Task<IActionResult> Index()
        {
            var dsvnContext = _context.Cabin.Include(c => c.CabinCategoryCodeNavigation).Include(c => c.TrainCodeNavigation);
            return View(await dsvnContext.ToListAsync());
        }

        // GET: Admin/Cabins/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cabin = await _context.Cabin
                .Include(c => c.CabinCategoryCodeNavigation)
                .Include(c => c.TrainCodeNavigation)
                .Include(c => c.Seat).ThenInclude(x=>x.FloorCodeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cabin == null)
            {
                return NotFound();
            }

            return View(cabin);
        }

        // GET: Admin/Cabins/Create
        public IActionResult Create()
        {
            ViewData["CabinCategoryCode"] = new SelectList(_context.CabinCategory, "Code", "Code");
            ViewData["TrainCode"] = new SelectList(_context.Train, "Code", "Code");
            return View();
        }

        // POST: Admin/Cabins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CabinCategoryCode,Index,TrainCode")] Cabin cabin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cabin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CabinCategoryCode"] = new SelectList(_context.CabinCategory, "Code", "Code", cabin.CabinCategoryCode);
            ViewData["TrainCode"] = new SelectList(_context.Train, "Code", "Code", cabin.TrainCode);
            return View(cabin);
        }

        // GET: Admin/Cabins/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cabin = await _context.Cabin.FindAsync(id);
            if (cabin == null)
            {
                return NotFound();
            }
            ViewData["CabinCategoryCode"] = new SelectList(_context.CabinCategory, "Code", "Code", cabin.CabinCategoryCode);
            ViewData["TrainCode"] = new SelectList(_context.Train, "Code", "Code", cabin.TrainCode);
            return View(cabin);
        }

        // POST: Admin/Cabins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CabinCategoryCode,Index,TrainCode")] Cabin cabin)
        {
            if (id != cabin.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cabin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CabinExists(cabin.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CabinCategoryCode"] = new SelectList(_context.CabinCategory, "Code", "Code", cabin.CabinCategoryCode);
            ViewData["TrainCode"] = new SelectList(_context.Train, "Code", "Code", cabin.TrainCode);
            return View(cabin);
        }

        // GET: Admin/Cabins/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cabin = await _context.Cabin
                .Include(c => c.CabinCategoryCodeNavigation)
                .Include(c => c.TrainCodeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cabin == null)
            {
                return NotFound();
            }

            return View(cabin);
        }

        // POST: Admin/Cabins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var cabin = await _context.Cabin.FindAsync(id);
            _context.Cabin.Remove(cabin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CabinExists(long id)
        {
            return _context.Cabin.Any(e => e.Id == id);
        }
    }
}

TrainTicketSales/Controllers/SeatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrainTicketSales.Helpers;
using TrainTicketSales.Models.Entity;
using TrainTicketSales.ModelsViews;

namespace TrainTicketSales.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SeatsController : ControllerBase
    {
        private readonly DsvnContext _context;
        private readonly IDapper _dapper;

        public SeatsController(DsvnContext context, IDapper dapper)
        {
            _dapper = dapper;
            _context = context;
        }

        // GET: api/Seats
        [HttpGet("GetByTrain")]
        public async Task<IEnumerable<SeatViewModel>> GetSeatByCabin(long cabinId)
        {
            var parameters = new DynamicParameters();
            parameters.Add("@cabinId", cabinId);
            return await _dapper.GetMultiByStoreProcedureAsync<SeatViewModel>("Seat_GetByCabin", parameters, commandType: CommandType.StoredProcedure);
        }

        // GET: api/Seats/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Seat>> GetSeat(long id)
        {
            var seat = await _context.Seat.FindAsync(id);

            if (seat == null)
            {
                return NotFound();
            }

            return seat;
        }

        // PUT: api/Seats/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutSeat(long id, Seat seat)
        {
            if (id != seat.Id)
            {
                return BadRequest();
            }

            _context.Entry(seat).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SeatExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Seats
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Seat>> PostSeat(Seat seat)
        {
            _context.Seat.Add(seat);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetSeat", new { id = seat.Id }, seat);
        }

        // DELETE: api/Seats/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteSeat(long id)
        {
            var seat = await _context.Seat.FindAsync(id);
            if (seat == null)
            {
                return NotFound();
            }

            _context.Seat.Remove(seat);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool SeatExists(long id)
        {
            return _context.Seat.Any(e => e.Id == id);
        }
    }
}

TrainTicketSales/Areas/Admin/Views/Cabins/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Cabin

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Cabin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CabinCategoryCode" class="control-label"></label>
                <select asp-for="CabinCategoryCode" class ="form-control" asp-items="ViewBag.CabinCategoryCode"></select>
            </div>
            <div class="form-group">
                <label asp-for="Index" class="control-label"></label>
                <input asp-for="Index" class="form-control" />
                <span asp-validation-for="Index" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainCode" class="control-label"></label>
                <select asp-for="TrainCode" class ="form-control" asp-items="ViewBag.TrainCode"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TrainTicketSales/Areas/Admin/Views/Cabins/Delete.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Cabin

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cabin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Index)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Index)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CabinCategoryCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CabinCategoryCodeNavigation.Code)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrainCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrainCodeNavigation.Code)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TrainTicketSales/Areas/Admin/Views/Cabins/Details.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Cabin

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Cabin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Index)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Index)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CabinCategoryCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CabinCategoryCodeNavigation.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrainCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrainCodeNavigation.Code)
        </dd>
    </dl>
    <hr />
    <h4>Ghế thuộc khoang  </h4>
    <table id="tb" class="table">
    <thead>
        <tr>
            <th>
                STT
            </th>           
            <th>
                Tầng 
            </th>            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Seat) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Index)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.FloorCodeNavigation.Name)
            </td>
            
            <td>                
                <a asp-controller="Seats" asp-action="Details" asp-route-id="@item.Id">Details</a> 
                  @*<a href="@Url.Action("Details", "Seats", new {id =@item.Id})"> Details</a>|*@                
            </td>
        </tr>
}
    </tbody>
</table>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
@section Script {
    <script>
        // Call the dataTables jQuery plugin
$(document).ready(function() {
  $('#tb').DataTable();
});
    </script>
}

TrainTicketSales/Areas/Admin/Views/Cabins/Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Cabin

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Cabin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CabinCategoryCode" class="control-label"></label>
                <select asp-for="CabinCategoryCode" class="form-control" asp-items="ViewBag.CabinCategoryCode"></select>
                <span asp-validation-for="CabinCategoryCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Index" class="control-label"></label>
                <input asp-for="Index" class="form-control" />
                <span asp-validation-for="Index" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainCode" class="control-label"></label>
                <select asp-for="TrainCode" class="form-control" asp-items="ViewBag.TrainCode"></select>
                <span asp-validation-for="TrainCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TrainTicketSales/Areas/Admin/Views/Cabins/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<TrainTicketSales.Models.Entity.Cabin>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Index)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CabinCategoryCodeNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrainCodeNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Index)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CabinCategoryCodeNavigation.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrainCodeNavigation.Code)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>