TrainTicketSales/Models/Entity/Train.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class Train
    {
        public Train()
        {
            Cabin = new HashSet<Cabin>();
            Schedule = new HashSet<Schedule>();
        }

        public string Code { get; set; }
        public string Name { get; set; }
        public string Des { get; set; }

        public virtual ICollection<Cabin> Cabin { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}

TrainTicketSales/Areas/Admin/Controllers/TrainsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrainTicketSales.Models.Entity;

namespace TrainTicketSales.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TrainsController : Controller
    {
        private readonly DsvnContext _context;

        public TrainsController(DsvnContext context)
        {
            _context = context;
        }

        // GET: Admin/Trains
        public async Task<IActionResult> Index()
        {
            string token = HttpContext.Session.GetString("Token");
            if (token == null)
            {
                return RedirectToAction("Login", "Home");
            }

            return View(await _context.Train.ToListAsync());
        }

        // GET: Admin/Trains/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var train = await _context.Train.Include(x=>x.Cabin)
                .FirstOrDefaultAsync(m => m.Code == id);
            if (train == null)
            {
                return NotFound();
            }

            return View(train);
        }

        // GET: Admin/Trains/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Trains/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Code,Name,Des")] Train train)
        {
            if (ModelState.IsValid)
            {
                _context.Add(train);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(train);
        }

        // GET: Admin/Trains/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var train = await _context.Train.FindAsync(id);
            if (train == null)
            {
                return NotFound();
            }
            return View(train);
        }

        // POST: Admin/Trains/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Code,Name,Des")] Train train)
        {
            if (id != train.Code)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(train);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainExists(train.Code))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(train);
        }

        // GET: Admin/Trains/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var train = await _context.Train
                .FirstOrDefaultAsync(m => m.Code == id);
            if (train == null)
            {
                return NotFound();
            }

            return View(train);
        }

        // POST: Admin/Trains/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var train = await _context.Train.FindAsync(id);
            _context.Train.Remove(train);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainExists(string id)
        {
            return _context.Train.Any(e => e.Code == id);
        }
    }
}

TrainTicketSales/Controllers/TrainsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrainTicketSales.Models.Entity;

namespace TrainTicketSales.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TrainsController : ControllerBase
    {
        private readonly DsvnContext _context;

        public TrainsController(DsvnContext context)
        {
            _context = context;
        }

        // GET: api/Trains
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Train>>> GetTrain()
        {
            var result=await _context.Train.ToListAsync();
            //foreach (var item in result)
            //{
            //    item.Cabin=_context.Cabin.Where(x=>x.TrainCode==item.Code).ToList();
            //    foreach (var item1 in item.Cabin)
            //    {
            //        item1.Seat=_context.Seat.Where(x=>x.CabinId==item1.Id).ToList();
            //    }
            //}
            return result;
        }

        // GET: api/Trains/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Train>> GetTrain(string id)
        {
            var train = await _context.Train.FindAsync(id);

            if (train == null)
            {
                return NotFound();
            }

            return train;
        }

        // PUT: api/Trains/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutTrain(string id, Train train)
        {
            if (id != train.Code)
            {
                return BadRequest();
            }

            _context.Entry(train).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TrainExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Trains
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Train>> PostTrain(Train train)
        {
            _context.Train.Add(train);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateException)
            {
                if (TrainExists(train.Code))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return CreatedAtAction("GetTrain", new { id = train.Code }, train);
        }

        // DELETE: api/Trains/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteTrain(string id)
        {
            var train = await _context.Train.FindAsync(id);
            if (train == null)
            {
                return NotFound();
            }

            _context.Train.Remove(train);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool TrainExists(string id)
        {
            return _context.Train.Any(e => e.Code == id);
        }
    }
}

TrainTicketSales/Areas/Admin/Views/Trains/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Train

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Train</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Des" class="control-label"></label>
                <input asp-for="Des" class="form-control" />
                <span asp-validation-for="Des" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TrainTicketSales/Areas/Admin/Views/Trains/Delete.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Train

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Train</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Des)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Des)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Code" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TrainTicketSales/Areas/Admin/Views/Trains/Details.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Train

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Train</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Des)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Des)
        </dd>

    </dl>
    <hr />
    <h4>Tổng số khoang</h4>
    <table id="tb" class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Cabin.ToList()[0].Index)
                </th>
                <th>
                    Cabin Code
                </th>
                <th>
                    Des
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cabin)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Index)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CabinCategoryCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CabinCategoryCodeNavigation.Name)
                    </td>
                    <td>


                        <a href="@Url.Action("Details", "Cabins", new {id =@item.Id})"> Details</a>|

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Code">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
@section Script {
<script>
            // Call the dataTables jQuery plugin
    $(document).ready(function() {
      $('#tb').DataTable();
    });
</script>
}

TrainTicketSales/Areas/Admin/Views/Trains/Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Train

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Train</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Code" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Des" class="control-label"></label>
                <input asp-for="Des" class="form-control" />
                <span asp-validation-for="Des" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TrainTicketSales/Areas/Admin/Views/Trains/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<TrainTicketSales.Models.Entity.Train>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table id="tb" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Des)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Des)
            </td>
            <td>
                
                <a href="@Url.Action("Details", "Trains", new {id =@item.Code})"> Chi tiết</a>
                @*<a asp-action="Details" asp-route-id="@item.Code">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Code">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>
@section Script {
    <script>
        // Call the dataTables jQuery plugin
$(document).ready(function() {
  $('#tb').DataTable();
});
    </script>
}