TrainTicketSales/Models/Entity/SaleOrder.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class SaleOrder
    {
        public SaleOrder()
        {
            SaleOrderDetail = new HashSet<SaleOrderDetail>();
        }

        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public DateTime? OrderDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string IdentityCard { get; set; }
        /// <summary>
        /// 1: đặt mua; 2: chấp nhận bán; 3: trả tiền; 4: xác nhận nhận tiền, 5:  giao vé, 6: hoãn, 7: đổi chuyển
        /// </summary>
        public int? Status { get; set; }

        public virtual ICollection<SaleOrderDetail> SaleOrderDetail { get; set; }
    }
}

TrainTicketSales/Areas/Admin/Controllers/SaleOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrainTicketSales.Helpers;
using TrainTicketSales.Models.Entity;
using TrainTicketSales.ModelsViews;

namespace TrainTicketSales.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SaleOrdersController : Controller
    {
        private readonly DsvnContext _context;
        private readonly IDapper _dapper;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public SaleOrdersController(DsvnContext context, IDapper dapper, IWebHostEnvironment webHostEnvironment, IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _dapper = dapper;
            _context = context;
            _hostingEnvironment = webHostEnvironment;
        }

        // GET: Admin/SaleOrders
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            string token = HttpContext.Session.GetString("Token");
            if (token == null)
            {
                return RedirectToAction("Login", "Home");
            }



            //var model= await _context.SaleOrder.Include(x=>x.SaleOrderDetail).ToListAsync();
            //return Json(new { status = true, result = model });
            return View(await _context.SaleOrder.Include(x => x.SaleOrderDetail).ToListAsync());
            //return Json(new { status = true, result = model });
        }

        [HttpGet]
        public async Task<JsonResult> Index1()
        {
            string token = HttpContext.Session.GetString("Token");

            if (token == null)
            {

                return null;
            }

            string domain = _httpContextAccessor.HttpContext.Request.Host.Value;
            string scheme = _httpContextAccessor.HttpContext.Request.Scheme;
            string delimiter = System.Uri.SchemeDelimiter;
            string fullDomainToUse = scheme + delimiter + domain;
            var parameters = new DynamicParameters();
            parameters.Add("@url", fullDomainToUse + "/Admin/SaleOrders/Edit/");
            parameters.Add("@id", 0);

            var result = await _dapper.GetMultiByStoreProcedureAsync<SaleOrderViewModel>("SaleOrders_GetAll", parameters, commandType: CommandType.StoredProcedure);
            if (result.Count() > 0)
            {
                return Json(new { status = true, result = result });
            }
            return Json(new { status = false, result = "" });
        }

        // GET: Admin/SaleOrders/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parameters = new DynamicParameters();
            parameters.Add("@url", "");
            parameters.Add("@id", id);
            var result = await _dapper.GetMultiByStoreProcedureAsync<SaleOrderViewModel>("SaleOrders_GetAll", parameters, commandType: CommandType.StoredProcedure);          


            if (result == null)
            {
                return NotFound();
            }
            return View(result.ToList()[0]);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public  async Task<JsonResult> SaveSaleOrderStatus(long id, int status)
        {
            string token = HttpContext.Session.GetString("Token");

            if (token == null)
            {
                 return Json(new { status = false, result = ""});

            }
            string domain = _httpContextAccessor.HttpContext.Request.Host.Value;
            string scheme = _httpContextAccessor.HttpContext.Request.Scheme;
            string delimiter = System.Uri.SchemeDelimiter;
            string fullDomainToUse = scheme + delimiter + domain;

            var model = _context.SaleOrder.Where(x => x.Id == id).Include(x => x.SaleOrderDetail).FirstOrDefault();

            if (model != null)
            {
                model.Status = status;
                _context.Update(model);
                await _context.SaveChangesAsync();
                switch (status)
                {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                    case 4:

                        foreach (var item in model.SaleOrderDetail)
                        {
                            var seatDetail = _context.SeatDetail.Find(item.SeatDetailId);
                            if (seatDetail != null)
                            {
                                seatDetail.Status = 2;// dang giu cho
                                _context.Update(model);
                            }

                        }
                        break;
                    case 5:
                        foreach (var item in model.SaleOrderDetail)
                        {
                            var seatDetail = _context.SeatDetail.Find(item.SeatDetailId);
                            if (seatDetail != null)
                            {
                                seatDetail.Status = 1;// dang giu cho
                                _context.Update(model);
                            }

                        }
                        break;
                    case 6:
                    case 7:
                        foreach (var item in model.SaleOrderDetail)
                        {
                            var seatDetail = _context.SeatDetail.Find(item.SeatDetailId);
                            if (seatDetail != null)
                            {
                                seatDetail.Status = 0;// dang giu cho
                                _context.Update(model);
                            }

                        }
                        break;
                    default:
                        break;
                }
                await _context.SaveChangesAsync();
            }
            return Json(new { status = true, result = fullDomainToUse+ "/Admin/SaleOrders/Details/"+id.ToString()});
            
        }

        // GET: Admin/SaleOrders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/SaleOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,OrderDate,PhoneNumber,Email,IdentityCard")] SaleOrder saleOrder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(saleOrder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(saleOrder);
        }

        // GET: Admin/SaleOrders/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parameters = new DynamicParameters();
            parameters.Add("@url", "");
            parameters.Add("@id", id);
            var result = await _dapper.GetMultiByStoreProcedureAsync<SaleOrderViewModel>("SaleOrders_GetAll", parameters, commandType: CommandType.StoredProcedure);

            var parameters1 = new DynamicParameters();
            parameters1.Add("@id", id);
            result.ToList()[0].SaleOrderDetail = _dapper.GetMultiByStoreProcedure<SaleOrderDetailViewModel>("SaleOrderDetail_GetById", parameters1, commandType: CommandType.StoredProcedure);


            if (result == null)
            {
                return NotFound();
            }
            return View(result.ToList()[0]);
        }

        // POST: Admin/SaleOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,OrderDate,PhoneNumber,Email,IdentityCard")] SaleOrder saleOrder)
        {
            if (id != saleOrder.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(saleOrder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaleOrderExists(saleOrder.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(saleOrder);
        }

        // GET: Admin/SaleOrders/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saleOrder = await _context.SaleOrder
                .FirstOrDefaultAsync(m => m.Id == id);
            if (saleOrder == null)
            {
                return NotFound();
            }

            return View(saleOrder);
        }

        // POST: Admin/SaleOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {

TrainTicketSales/Controllers/SaleOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrainTicketSales.Models.Entity;

namespace TrainTicketSales.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SaleOrdersController : ControllerBase
    {
        private readonly DsvnContext _context;

        public SaleOrdersController(DsvnContext context)
        {
            _context = context;
        }

        // GET: api/SaleOrders
        [HttpGet]
        public async Task<ActionResult<IEnumerable<SaleOrder>>> GetSaleOrder()
        {
            return await _context.SaleOrder.Include(x=>x.SaleOrderDetail).ToListAsync();
        }

        // GET: api/SaleOrders/5
        [HttpGet("{id}")]
        public async Task<ActionResult<SaleOrder>> GetSaleOrder(long id)
        {
            var saleOrder = await _context.SaleOrder.Where(x=>x.Id==id).Include(x=>x.SaleOrderDetail).FirstOrDefaultAsync();

            if (saleOrder == null)
            {
                return NotFound();
            }

            return saleOrder;
        }

        // PUT: api/SaleOrders/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutSaleOrder(long id, SaleOrder saleOrder)
        {
            if (id != saleOrder.Id)
            {
                return BadRequest();
            }

            _context.Entry(saleOrder).State = EntityState.Modified;
            foreach (var item in saleOrder.SaleOrderDetail)
            {
                if(item.Id >0)
                {
                    _context.SaleOrderDetail.Add(item);
                }
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SaleOrderExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/SaleOrders
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<SaleOrder>> PostSaleOrder(SaleOrder saleOrder)
        {
            _context.SaleOrder.Add(saleOrder);
            await _context.SaveChangesAsync();

            //var headId= saleOrder.Id;
            //foreach (var item in saleOrder.SaleOrderDetail)
            //{
            //    item.SaleOrderId = headId;  
            //    _context.SaleOrderDetail.Add(item); 
            //}
            //await _context.SaveChangesAsync();
            return CreatedAtAction("GetSaleOrder", new { id = saleOrder.Id }, saleOrder);
        }

        // DELETE: api/SaleOrders/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteSaleOrder(long id)
        {
            var saleOrder = await _context.SaleOrder.FindAsync(id);
            if (saleOrder == null)
            {
                return NotFound();
            }

            _context.SaleOrder.Remove(saleOrder);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool SaleOrderExists(long id)
        {
            return _context.SaleOrder.Any(e => e.Id == id);
        }
    }
}

TrainTicketSales/Areas/Admin/Views/SaleOrders/Details.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.ModelsViews.SaleOrderViewModel
@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Chi tiết đơn hàng</h1>

<dl class="row">
    <dd><input type="hidden" id="id" value="@(Model.Id)"></dd>

    <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.OrderDate)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.OrderDate)
    </dd>
    <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.PhoneNumber)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.PhoneNumber)
    </dd>
    <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.Email)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.Email)
    </dd>
    <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.IdentityCard)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.IdentityCard)
    </dd>
        <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.Status)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.StatusName)
    </dd>
   

</dl>
<a asp-action="Index">Back to List</a>

TrainTicketSales/Areas/Admin/Views/SaleOrders/Edit.cshtml
@model TrainTicketSales.ModelsViews.SaleOrderViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>SaleOrder</h4>
<hr />
<div class="container">
    <div class="row">

        <div class="card card-body">
            <dl class="row">
                <dd><input type="hidden" id="id" value="@(Model.Id)"></dd>

                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.OrderDate)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.OrderDate)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.PhoneNumber)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.IdentityCard)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.IdentityCard)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Status)
                </dt>
                <dd class="col-sm-8">
                    <select id="cboStatus" class="form-select" aria-label="Default select example">
                        <option value="@Html.DisplayFor(model => model.Status)" selected> @Html.DisplayFor(model => model.StatusName)</option>
                        <option value="1">Đặt mua</option>
                        <option value="2">Chấp nhận bán</option>
                        <option value="3">Trả tiền</option>
                        <option value="4">Xác nhận nhận tiền</option>
                        <option value="5">Giao vé</option>
                        <option value="6">Hoãn </option>
                        <option value="7">Đổi chuyến</option>
                    </select>
                </dd>
            </dl>
            <hr>
            <div class="row">
                <table id="dtBasicExample" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                ID
                            </th>
                            <th>
                                SaleOrderId
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                IdentityCard
                            </th>
                            <th>
                                SeatID
                            </th>
                            <th>
                                SeatName
                            </th>
                            <th>
                                Price
                            </th>
                            <th>Status</th>
                            <th>ScheduleID</th>
                            <th>  </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.SaleOrderDetail)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SaleOrderId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IdentityCard)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SeatId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SeatName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Status)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ScheduleID)
                                </td>
                                @*<td>
                                    <a href="@Url.Action("Details", "SaleOrders", new {id =@item.Id,saleOrder=@item})">Hủy vé</a>|
                                    <a href="@Url.Action("Details", "SaleOrders", new {id =@item.Id,saleOrder=@item})">Xác nhận</a>|
                                    </td>*@
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <button onclick="saveStatus()" class="btn btn-primary"> Lưu trạng thái phiếu </button>
            </div>
        </div>

    </div>

</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Script {
<script>

    
function saveStatus() {    
        let data ={id:$("#id").val(),
        status:$("#cboStatus").val()
        };
        console.log(data);
        let url = '/Admin/SaleOrders/SaveSaleOrderStatus?id='+$("#id").val()+'&status='+$("#cboStatus").val();
        res = false;
        $.ajax({
            type: "POST",
            url: url,
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify(data),
           
            success: function (response) {
                if (response.status) {
                    window.open(response.result, "_self")
                } else {
                    
                }
            }
        }
        );
        return res;
    }
</script>

    }

TrainTicketSales/Areas/Admin/Views/SaleOrders/Index.cshtml
@model IEnumerable<TrainTicketSales.Models.Entity.SaleOrder>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Danh sách đặt vé</h1>

    <div class="table-responsive">
        <table id="dtBasicExample" class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Code)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.OrderDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IdentityCard)
                    </th>
                    <th>
                        Total
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @* @foreach (var item in Model) {
                    <tr>
                    <td>
                    @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>
                    <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                    @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                    @Html.DisplayFor(modelItem => item.IdentityCard)
                    </td>
                    <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a href="@Url.Action("Details", "SaleOrders", new {id =@item.Id,saleOrder=@item})"> Details</a>
                    <a href="@Url.Action("Edit", "SaleOrders", new {id =@item.Id})"> Clients</a>

                    </td>
                    </tr>
                    }*@
            </tbody>
        </table>
    </div>


@section Script{
<script>
                var table = null;
                var BaoCao = (function () {
        return {
            renderDatatable: function () {
                if (table) {
                    table.destroy();
                }

                 table = $('#dtBasicExample').DataTable({
                    pageLength: 25,
                    order: [0, 'asc'],
                    ajax: {
                        url: '/Admin/SaleOrders/Index1',

                        dataSrc: function (res) {
                            if(res.status)
                            {
                            console.log(res.result);
                            return res.result;
                            }
                            else
                            {
                                return "";
                            }
                        }
                        //dataSrc: ""
                    },
                    columns: [
                        {
                            "title": "STT",
                            "width": "5%",
                            "data": null,
                        },
                        //{
                        //    "title": "Mã đặt vé",
                        //    "data": "code",
                        //},
                        {
                            "title": "Tên người đặt",
                            "data": null,
                            "mRender": function (data, type, full) {
                                //return `<span class="font-weight-bold">${data.name}</span>`;
                                return `<a href="${data.actionLink}"><span class="font-weight-bold">${data.name}</span></a> `;
                            }
                        },
                        {
                            "title": "Mã đặt vé",
                            "data": "code",
                        },
                        {
                            "title": "Trạng thái",
                            "data": "status",
                        },
                        {
                            "title": "Ngày đặt vé",
                            "data": "orderDate",
                        },
                        {
                            "title": "Số điện thoại",
                            "data": "phoneNumber",
                        },
                        {
                            "title": "Email",
                            "data": "email",
                        },
                        {
                            "title": "CMND",
                            "data": "identityCard",
                        },
                        {
                            "title": "Tổng tiền",
                            "data": "total",
                        },
                        //{
                        //    "title": "",
                        //    "data": "",
                        //},
                    ]
                });
                table.on('order.dt search.dt', function () {
                    table.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                        cell.innerHTML = i + 1;
                    });
                }).draw();

                $('.dataTables_length').addClass('bs-select');
            },
            //triggerControls: () => {
            //    $("#loctheonam").on('change', function () {
            //        year = $(this).val();
            //        BaoCao.renderDatatable(year);
            //    })
            //},
        }
    })();
    BaoCao.renderDatatable();
    //BaoCao.triggerControls();
</script>
}