TrainTicketSales/Models/Entity/Schedule.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class Schedule
    {
        public Schedule()
        {
            SeatDetail = new HashSet<SeatDetail>();
        }

        public long Id { get; set; }
        public long? BeginStationId { get; set; }
        public long? EndStationId { get; set; }
        public string TrainCode { get; set; }
        public DateTime? DateBegin { get; set; }
        public DateTime? DateEnd { get; set; }

        public virtual Station BeginStation { get; set; }
        public virtual Station EndStation { get; set; }
        public virtual Train TrainCodeNavigation { get; set; }
        public virtual ICollection<SeatDetail> SeatDetail { get; set; }
    }
}

TrainTicketSales/Areas/Admin/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrainTicketSales.Models.Entity;
using TrainTicketSales.ModelsViews;

namespace TrainTicketSales.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SchedulesController : Controller
    {
        private readonly DsvnContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public SchedulesController(DsvnContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: Admin/Schedules
        public async Task<IActionResult> Index()
        {
            string token = HttpContext.Session.GetString("Token");
            if (token == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var dsvnContext = _context.Schedule.Include(s => s.BeginStation).Include(s => s.EndStation).Include(s => s.TrainCodeNavigation);
            return View(await dsvnContext.ToListAsync());
        }

        // GET: Admin/Schedules/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule
                .Include(s => s.BeginStation)
                .Include(s => s.EndStation)
                .Include(s => s.TrainCodeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }

        // GET: Admin/Schedules/Create
        public IActionResult Create()
        {
            ViewData["BeginStationId"] = new SelectList(_context.Station, "Id", "Code");
            ViewData["EndStationId"] = new SelectList(_context.Station, "Id", "Code");
            ViewData["TrainCode"] = new SelectList(_context.Train, "Code", "Code");
            ScheduleAdminViewModel scheduleAdminViewModel = new ScheduleAdminViewModel();
            scheduleAdminViewModel.BeginStation = _context.Station.ToList();
            scheduleAdminViewModel.EndStation = _context.Station.ToList();
            return View();

        }

        // POST: Admin/Schedules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<JsonResult> Create([FromBody] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                _context.Add(schedule);
                await _context.SaveChangesAsync();
                string domain = _httpContextAccessor.HttpContext.Request.Host.Value;
                string scheme = _httpContextAccessor.HttpContext.Request.Scheme;
                string delimiter = System.Uri.SchemeDelimiter;
                string fullDomainToUse = scheme + delimiter + domain;
                return Json(new { status = true, result = fullDomainToUse + "/Admin/Schedules/Index" });
            }
            return Json(new { status = false, result =  "/Admin/Home/Login" });

        }

        // GET: Admin/Schedules/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule.FindAsync(id);
            if (schedule == null)
            {
                return NotFound();
            }
            ViewData["BeginStationId"] = new SelectList(_context.Station, "Id", "Code", schedule.BeginStationId);
            ViewData["EndStationId"] = new SelectList(_context.Station, "Id", "Code", schedule.EndStationId);
            ViewData["TrainCode"] = new SelectList(_context.Train, "Code", "Code", schedule.TrainCode);
            return View(schedule);
        }
        [HttpGet]
        public async Task<JsonResult> GetStation()
        {
            string token = HttpContext.Session.GetString("Token");

            if (token == null)
            {

                return null;
            }
            var result = await _context.Station.ToListAsync();

            return Json(new { status = true, result = result });

        }
        [HttpGet]
        public async Task<JsonResult> GetTrain()
        {
            string token = HttpContext.Session.GetString("Token");

            if (token == null)
            {

                return null;
            }
            var result = await _context.Train.ToListAsync();

            return Json(new { status = true, result = result });

        }
        // POST: Admin/Schedules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public async Task<IActionResult> Edit(long id, [Bind("Id,BeginStationId,EndStationId,TrainCode,DateBegin,DateEnd")] Schedule schedule)
        {
            if (id != schedule.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schedule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduleExists(schedule.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BeginStationId"] = new SelectList(_context.Station, "Id", "Code", schedule.BeginStationId);
            ViewData["EndStationId"] = new SelectList(_context.Station, "Id", "Code", schedule.EndStationId);
            ViewData["TrainCode"] = new SelectList(_context.Train, "Code", "Code", schedule.TrainCode);
            return View(schedule);
        }

        // GET: Admin/Schedules/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule
                .Include(s => s.BeginStation)
                .Include(s => s.EndStation)
                .Include(s => s.TrainCodeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schedule == null)
            {
                return NotFound();
            }
            return View(schedule);
        }

        // POST: Admin/Schedules/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var schedule = await _context.Schedule.FindAsync(id);
            _context.Schedule.Remove(schedule);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScheduleExists(long id)
        {
            return _context.Schedule.Any(e => e.Id == id);
        }
    }
}

TrainTicketSales/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using TrainTicketSales.Helpers;
using TrainTicketSales.Models.Entity;
using TrainTicketSales.ModelsViews;

namespace TrainTicketSales.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SchedulesController : ControllerBase
    {
        private readonly DsvnContext _context;
        private readonly IDapper _dapper;
        public SchedulesController(DsvnContext context, IDapper dapper)
        {
            _context = context;
            _dapper = dapper;
        }

        // GET: api/Schedules
        [HttpGet("GetTrain")]
        public async Task<IEnumerable<ScheduleViewModel>> GetSchedule(long StationBegin, long StationEnd, DateTime date)
        {
            List<ScheduleViewModel> schedules = new List<ScheduleViewModel>();
            
            var val = await _context.Schedule.Where(x => x.BeginStationId == StationBegin && x.EndStationId == StationEnd && x.DateBegin == date).ToListAsync();
            foreach (var item in val)
            {
                List<TrainViewModel> TrainList = new List<TrainViewModel>();
                var scheduleViewModel = new ScheduleViewModel();

                scheduleViewModel.Id = item.Id;
                scheduleViewModel.DateBegin = item.DateBegin;
                scheduleViewModel.DateEnd = item.DateEnd;
                scheduleViewModel.BeginStationId = item.BeginStationId;
                scheduleViewModel.EndStationId = item.EndStationId;
                scheduleViewModel.TrainCode = item.TrainCode;

                var train = _context.Train.Where(x => x.Code == item.TrainCode).Include(x => x.Cabin).ToList()[0];
                TrainViewModel trainModel = new TrainViewModel();
                trainModel.Code = train.Code;
                trainModel.Name = train.Name;
                trainModel.Des = train.Des;
                var parameters = new DynamicParameters();
                parameters.Add("@trainCode", train.Code);
                trainModel.Cabin = _dapper.GetMultiByStoreProcedure<CabinViewModel>("Cabin_GetByTrain", parameters, commandType: CommandType.StoredProcedure);
                TrainList.Add(trainModel);
                scheduleViewModel.TrainsList=TrainList;

                schedules.Add(scheduleViewModel);
            }
            //var result = JsonConvert.DeserializeObject<IEnumerable<ScheduleViewModel>>(JsonConvert.SerializeObject(val));
            return schedules;
        }

        // GET: api/Schedules/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Schedule>> GetSchedule(long id)
        {
            var schedule = await _context.Schedule.FindAsync(id);

            if (schedule == null)
            {
                return NotFound();
            }

            return schedule;
        }

        // PUT: api/Schedules/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutSchedule(long id, Schedule schedule)
        {
            if (id != schedule.Id)
            {
                return BadRequest();
            }

            _context.Entry(schedule).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ScheduleExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Schedules
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Schedule>> PostSchedule(Schedule schedule)
        {
            _context.Schedule.Add(schedule);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetSchedule", new { id = schedule.Id }, schedule);
        }

        // DELETE: api/Schedules/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteSchedule(long id)
        {
            var schedule = await _context.Schedule.FindAsync(id);
            if (schedule == null)
            {
                return NotFound();
            }

            _context.Schedule.Remove(schedule);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool ScheduleExists(long id)
        {
            return _context.Schedule.Any(e => e.Id == id);
        }
    }
}

TrainTicketSales/Areas/Admin/Views/Schedules/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Schedule;


@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Schedule</h4>
<hr />
<div class="row">
    <div class="container card card-body">
        @*<form asp-action="Create" method="post">*@
            <div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group col-sm-5">
                <label asp-for="BeginStationId" class="control-label">Ga đi</label>
                <select id="drpBeginStation" asp-for="BeginStationId" class="form-control" asp-items="ViewBag.EndStationId ">
                </select>

                <input type="hidden" asp-for="BeginStationId" />
            </div>
            <div class="form-group col-sm-5">
                <label asp-for="EndStationId" class="control-label">Ga đến</label>
                <select id="drpEndStation" asp-for="EndStationId" class="form-control" asp-items="ViewBag.EndStationId">
                </select>

                <input type="hidden" asp-for="EndStationId" />
            </div>
            <div class="form-group col-sm-5">
                <label asp-for="TrainCode" class="control-label">Tàu </label>
                <select id="TrainCode" asp-for="TrainCode" class="form-control" asp-items="ViewBag.TrainCode">
                </select>
            </div>
            <div class="form-group col-sm-5">
                <label asp-for="DateBegin" class="control-label">Ngày bắt đầu</label>
                <input id="DateBegin" type="datetime-local" asp-for="DateBegin" class="form-control" />
                <span asp-validation-for="DateBegin" class="text-danger"></span>
            </div>
            <div class="form-group col-sm-5">
                <label asp-for="DateEnd" class="control-label">Ngày đến</label>
                <input id="DateEnd" type="datetime-local" asp-for="DateEnd" class="form-control" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input onclick="save()" type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Script {
<script>

    var save = () => {
        let paramUpdate = {
        BeginStationId: $("#drpBeginStation").val(), // cá nhân
        EndStationId: $("#drpEndStation").val(),
        TrainCode: $("#TrainCode").val(),
        DateBegin: $("#DateBegin").val(),
        DateEnd: $("#DateEnd").val(),
        };
        let data = JSON.stringify(paramUpdate);
        console.log(data)
    let url = '/Admin/Schedules/Create';
    $.ajax({
        type: "POST",
        url: url,
        contentType: 'application/json; charset=utf-8',
        dataType: "json",
        data: data,
         success: function (response) {         
              if (response.status) {
                window.open(response.result, "_self")
            }


        }

    });

    }






                     var getStation = () => {
        let url = '/Admin/Schedules/GetStation';
        $.get(url).done(function (response) {
            console.log(response.result)
            let html = '`<option value="">Chọn ga</option>`';
            let flag = 0;
            $.each(response.result, function (i, e) {
                     html += `<option value="${e.id}">${e.name}</option>`;
            })
            $('#drpBeginStation').html(html);
            $('#drpEndStation').html(html);
        });
    }
     var getTrain = () => {
        let url = '/Admin/Schedules/GetTrain';
        $.get(url).done(function (response) {
            console.log(response.result)
            let html = '`<option value="">Chọn tàu</option>`';
            let flag = 0;
            $.each(response.result, function (i, e) {
                     html += `<option value="${e.code}">${e.name}</option>`;
            })
            $('#TrainCode').html(html);

        });
    }
    $(document).ready(async function () {
    getStation();
    getTrain();
    })

</script>

    }

TrainTicketSales/Areas/Admin/Views/Schedules/Delete.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers 
@model TrainTicketSales.Models.Entity.Schedule

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateBegin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateBegin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BeginStation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BeginStation.Code)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndStation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndStation.Code)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrainCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrainCodeNavigation.Code)
        </dd class>
    </dl>
    
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TrainTicketSales/Areas/Admin/Views/Schedules/Details.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Schedule

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Schedule</h4>
    <hr />
    <div class="container">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateBegin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateBegin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BeginStation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BeginStation.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndStation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndStation.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrainCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrainCodeNavigation.Code)
        </dd>
    </dl>
   
</div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TrainTicketSales/Areas/Admin/Views/Schedules/Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TrainTicketSales.Models.Entity.Schedule

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Schedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BeginStationId" class="control-label"></label>
                <select id="BeginStationId" asp-for="BeginStationId" class="form-control" asp-items="ViewBag.BeginStationId"></select>
                <span asp-validation-for="BeginStationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndStationId" class="control-label"></label>
                <select id ="EndStationId" asp-for="EndStationId" class="form-control" asp-items="ViewBag.EndStationId"></select>
                <span asp-validation-for="EndStationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainCode" class="control-label"></label>
                <select id="TrainCode" asp-for="TrainCode" class="form-control" asp-items="ViewBag.TrainCode"></select>
                <span asp-validation-for="TrainCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateBegin" class="control-label"></label>
                <input  type="datetime-local" asp-for="DateBegin" class="form-control" />
                <span asp-validation-for="DateBegin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input type="datetime-local" asp-for="DateEnd" class="form-control" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Script {
<script>

    var save = () => {
        let paramUpdate = {
        BeginStationId: $("#drpBeginStation").val(), // cá nhân
        EndStationId: $("#drpEndStation").val(),
        TrainCode: $("#TrainCode").val(),
        DateBegin: $("#DateBegin").val(),
        DateEnd: $("#DateEnd").val(),
        };
        let data = JSON.stringify(paramUpdate);
        console.log(data)
    let url = '/Admin/Schedules/Create';
    $.ajax({
        type: "POST",
        url: url,
        contentType: 'application/json; charset=utf-8',
        dataType: "json",
        data: data,
         success: function (response) {         
              if (response.status) {
                window.open(response.result, "_self")
            }


        }

    });

    }






                     var getStation = () => {
        let url = '/Admin/Schedules/GetStation';
        $.get(url).done(function (response) {
            console.log(response.result)
            let html = '`<option value="">Chọn ga</option>`';
            let flag = 0;
            $.each(response.result, function (i, e) {
                     html += `<option value="${e.id}">${e.name}</option>`;
            })
            $('#EndStationId').html(html);
            $('#BeginStationId').html(html);
        });
    }
     var getTrain = () => {
        let url = '/Admin/Schedules/GetTrain';
        $.get(url).done(function (response) {
            console.log(response.result)
            let html = '`<option value="">Chọn tàu</option>`';
            let flag = 0;
            $.each(response.result, function (i, e) {
                     html += `<option value="${e.code}">${e.name}</option>`;
            })
            $('#TrainCode').html(html);

        });
    }
    $(document).ready(async function () {
    getStation();
    getTrain();
    })

</script>

    }

TrainTicketSales/Areas/Admin/Views/Schedules/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<TrainTicketSales.Models.Entity.Schedule>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Danh sách lịch trình tàu</h1>

<p>
    
    <a href="@Url.Action("Create", "Schedules")"> Tạo mới</a>
</p>
<table id="tb" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateBegin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BeginStation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndStation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrainCodeNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateBegin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateEnd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeginStation.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndStation.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrainCodeNavigation.Code)
            </td>
            <td>
                <a href="@Url.Action("Details", "Schedules", new {id =@item.Id})"> Details</a>|
                @*<a href="@Url.Action("Edit", "Schedules", new {id =@item.Id})"> Edit</a>|*@
                <a href="@Url.Action("Delete", "Schedules", new {id =@item.Id})"> Delete</a>
                
              
            </td>
        </tr>
}
    </tbody>
</table>
@section Script {
    <script>
        // Call the dataTables jQuery plugin
$(document).ready(function() {
  $('#tb').DataTable();
});
    </script>
}